/* =====================================================================
   DATA — this is the part you own. Edit this file only; index.html
   never needs to change when you add, remove, or fix a resource.

   How to add a row:
     1. Get lat/lng by right-clicking any spot in Google Maps.
     2. region:   1=Northeast  2=Southeast  3=Midwest  4=Southwest  5=West
        (state → region mapping lives in scripts/make-regions.js)
     3. category: con | meetup | maker | school | gov
     4. url / address / phone / when may be "" if unknown — the popup
        simply omits empty fields. Never guess contact details.
     5. next: "YYYY-MM-DD" — machine-readable start date for dated events.
        Powers the Upcoming panel and expired-date flagging; omit for
        recurring meetups and undated entries.

   Data sweep: July 2026. This is a national map, so it carries the
   anchors — the cons, groups, spaces, schools, and hubs people actually
   use to plug into the community. Venues and schedules drift; the notes
   flag anything to re-verify. Florida has its own deep-dive map
   (florida-cyber-map) — only its statewide anchors are repeated here.
   ===================================================================== */
const RESOURCES = [
  // ---- 1 · NORTHEAST ----
  { name:"HOPE 26 (Hackers On Planet Earth)", category:"con", region:1, lat:40.7527, lng:-73.9935, city:"New York, NY", url:"https://www.hope.net", address:"New Yorker Hotel, 481 8th Ave, Manhattan", phone:"", next:"2026-08-14", when:"Aug 14–16, 2026", notes:"2600 Magazine's biennial-turned-annual hacker con — back in Manhattan; talks, villages, radio, art." },
  { name:"SummerCon", category:"con", region:1, lat:40.6944, lng:-73.9213, city:"Brooklyn, NY", url:"https://www.summercon.org", address:"", phone:"", when:"Annual — dates on site", notes:"One of the oldest hacker cons in America (since 1987) — single-track talks and a long bar tab." },
  { name:"BSidesNYC", category:"con", region:1, lat:40.7712, lng:-73.9882, city:"New York, NY", url:"https://bsidesnyc.org", address:"", phone:"", when:"See site for next edition", notes:"NYC's community security con — historically at John Jay College; free/cheap, volunteer-run." },
  { name:"BSides Boston", category:"con", region:1, lat:42.3601, lng:-71.0589, city:"Boston, MA", url:"", address:"", phone:"", when:"", notes:"Boston's BSides — verify the current edition via bsides.org or community socials." },
  { name:"BSides Philly", category:"con", region:1, lat:39.9526, lng:-75.1652, city:"Philadelphia, PA", url:"", address:"", phone:"", when:"Annual, winter — see site", notes:"Philadelphia's community security con — verify current site via the Security BSides wiki." },
  { name:"BSides Pittsburgh", category:"con", region:1, lat:40.4406, lng:-79.9959, city:"Pittsburgh, PA", url:"https://bsidespgh.com", address:"", phone:"", when:"Annual — see site", notes:"Pittsburgh's community con in a serious security town (CMU, CERT, big vendor offices)." },
  { name:"BSidesROC", category:"con", region:1, lat:43.1566, lng:-77.6088, city:"Rochester, NY", url:"https://bsidesroc.com", address:"", phone:"", when:"Annual, spring", notes:"Rochester's grassroots con — strong RIT student pipeline, lockpick village, CTF." },
  { name:"BSidesCharm", category:"con", region:1, lat:39.4015, lng:-76.6019, city:"Towson, MD", url:"https://www.bsidescharm.org", address:"", phone:"", when:"Annual, spring", notes:"Baltimore-area BSides — heavy NSA/Fort Meade crowd; CTF and villages." },
  { name:"CSAW (NYU)", category:"con", region:1, lat:40.6942, lng:-73.9866, city:"Brooklyn, NY", url:"https://www.csaw.io", address:"NYU Tandon, 6 MetroTech Center, Brooklyn", phone:"", when:"Annual, November", notes:"The largest student-run security event in the world — CTF finals, embedded security, policy; finals week open to visitors." },
  { name:"NYC2600", category:"meetup", region:1, lat:40.7587, lng:-73.9707, city:"New York, NY", url:"https://www.2600.com/meetings", address:"Citigroup Center food court, 153 E 53rd St, Manhattan", phone:"", when:"1st Friday, 5pm", notes:"The original 2600 meeting, in the magazine's hometown — open to absolutely everyone." },
  { name:"OWASP New York City", category:"meetup", region:1, lat:40.7128, lng:-74.0060, city:"New York, NY", url:"https://owasp.org/chapters/", address:"", phone:"", when:"See Meetup for events", notes:"AppSec chapter for the NYC metro — find the chapter page + Meetup via owasp.org." },
  { name:"OWASP Boston", category:"meetup", region:1, lat:42.3601, lng:-71.0589, city:"Boston, MA", url:"https://owasp.org/chapters/", address:"", phone:"", when:"Monthly — see Meetup", notes:"One of the longest-running OWASP chapters; talks and networking." },
  { name:"DC401 (DEF CON Group)", category:"meetup", region:1, lat:41.8240, lng:-71.4128, city:"Providence, RI", url:"https://dc401.org", address:"", phone:"", when:"Monthly — see site", notes:"Rhode Island's DEF CON group — talks, CTF practice, hardware nights." },
  { name:"DC215 (DEF CON Group)", category:"meetup", region:1, lat:39.9600, lng:-75.1600, city:"Philadelphia, PA", url:"", address:"", phone:"", when:"", notes:"Philadelphia DEF CON group — confirm current status via the DEF CON Groups directory (forum.defcon.org)." },
  { name:"NYC Resistor", category:"maker", region:1, lat:40.6849, lng:-73.9831, city:"Brooklyn, NY", url:"https://www.nycresistor.com", address:"87 3rd Ave, Brooklyn", phone:"", when:"Craft Night Thursdays — see site", notes:"Storied Brooklyn hackerspace — 'We learn, share, and make things.'" },
  { name:"Hack Manhattan", category:"maker", region:1, lat:40.7383, lng:-73.9976, city:"New York, NY", url:"https://hackmanhattan.com", address:"137 W 14th St, Manhattan", phone:"", when:"Open house Tuesdays — see site", notes:"Community hackerspace — electronics, 3D printing, amateur radio." },
  { name:"HacDC", category:"maker", region:1, lat:38.9339, lng:-77.0344, city:"Washington, DC", url:"https://www.hacdc.org", address:"1525 Newton St NW, Washington", phone:"", when:"", notes:"DC's original hackerspace — radio club, microcontroller nights, open meetings." },
  { name:"Artisan's Asylum", category:"maker", region:1, lat:42.3550, lng:-71.1300, city:"Boston (Allston), MA", url:"https://www.artisansasylum.com", address:"", phone:"", when:"", notes:"One of the largest nonprofit makerspaces in the US — full shops plus electronics." },
  { name:"Unallocated Space", category:"maker", region:1, lat:39.1300, lng:-76.6800, city:"Severn, MD", url:"https://www.unallocatedspace.org", address:"", phone:"", when:"", notes:"Hackerspace in the NSA/Fort Meade orbit — electronics, retro computing, security nights." },
  { name:"MakeHaven", category:"maker", region:1, lat:41.3033, lng:-72.9140, city:"New Haven, CT", url:"https://www.makehaven.org", address:"770 Chapel St, New Haven", phone:"", when:"", notes:"Connecticut's big community makerspace — tours weekly." },
  { name:"Carnegie Mellon — CyLab / picoCTF", category:"school", region:1, lat:40.4433, lng:-79.9436, city:"Pittsburgh, PA", url:"https://www.cylab.cmu.edu", address:"CMU campus, Pittsburgh", phone:"", when:"", notes:"Top security research institute; home of PPP (record DEF CON CTF wins), picoCTF, and the CERT division at the SEI." },
  { name:"MIT CSAIL", category:"school", region:1, lat:42.3616, lng:-71.0906, city:"Cambridge, MA", url:"https://www.csail.mit.edu", address:"32 Vassar St, Cambridge", phone:"", when:"", notes:"Security/crypto research powerhouse; public talks and seminars are frequent." },
  { name:"NYU Center for Cybersecurity", category:"school", region:1, lat:40.6944, lng:-73.9860, city:"Brooklyn, NY", url:"https://cyber.nyu.edu", address:"NYU Tandon, Brooklyn", phone:"", when:"", notes:"Runs the OSIRIS Lab (open student hacking lab) and CSAW." },
  { name:"RIT Global Cybersecurity Institute", category:"school", region:1, lat:43.0845, lng:-77.6749, city:"Rochester, NY", url:"https://www.rit.edu/cybersecurity/", address:"RIT campus, Rochester", phone:"", when:"", notes:"Dedicated cyber building + range; hosts the Collegiate Penetration Testing Competition (CPTC)." },
  { name:"NSA / US Cyber Command", category:"gov", region:1, lat:39.1080, lng:-76.7710, city:"Fort Meade, MD", url:"https://www.nsa.gov", address:"Fort Meade", phone:"", when:"", notes:"The center of gravity of US cyber — GenCyber camps, CAE school designations, Codebreaker Challenge; the free National Cryptologic Museum next door is worth the stop." },
  { name:"NIST NCCoE", category:"gov", region:1, lat:39.0951, lng:-77.2010, city:"Rockville, MD", url:"https://www.nccoe.nist.gov", address:"9700 Great Seneca Hwy, Rockville", phone:"", when:"", notes:"National Cybersecurity Center of Excellence — the lab behind the SP 1800 practice guides; hosts public workshops." },

  // ---- 2 · SOUTHEAST ----
  { name:"CarolinaCon", category:"con", region:2, lat:35.9940, lng:-78.8986, city:"Durham, NC", url:"https://www.carolinacon.org", address:"", phone:"", when:"Annual, spring", notes:"Long-running, famously cheap community hacker con for the Triangle." },
  { name:"BSides Atlanta", category:"con", region:2, lat:33.7490, lng:-84.3880, city:"Atlanta, GA", url:"", address:"", phone:"", when:"Annual — see site", notes:"Atlanta's community con — verify current edition via the Security BSides wiki." },
  { name:"BSides Augusta", category:"con", region:2, lat:33.4735, lng:-82.0105, city:"Augusta, GA", url:"https://www.bsidesaugusta.org", address:"", phone:"", when:"Annual, fall", notes:"Punches far above its weight — Army Cyber / NSA Georgia crowd from next-door Fort Eisenhower." },
  { name:"BSides Nashville", category:"con", region:2, lat:36.1627, lng:-86.7816, city:"Nashville, TN", url:"", address:"", phone:"", when:"Annual — see site", notes:"Middle Tennessee's community con — verify current edition via the Security BSides wiki." },
  { name:"BSides Knoxville", category:"con", region:2, lat:35.9606, lng:-83.9207, city:"Knoxville, TN", url:"", address:"", phone:"", when:"Annual — see site", notes:"East Tennessee BSides with a strong Oak Ridge contingent." },
  { name:"TechNet Augusta (AFCEA)", category:"con", region:2, lat:33.4710, lng:-81.9750, city:"Augusta, GA", url:"https://www.afcea.org", address:"Augusta Convention Center", phone:"", when:"Annual, August", notes:"The Army cyber/signal community's big industry con — good for defense-side networking and hiring." },
  { name:"BSides Tampa", category:"con", region:2, lat:28.0645, lng:-82.4130, city:"Tampa, FL", url:"https://bsidestampa.net", address:"USF Marshall Student Center, Tampa", phone:"", when:"Annual, spring", notes:"2,000+ attendees. Florida anchor — see the Florida Cyber Resource Map for the full state deep-dive." },
  { name:"BSides Orlando", category:"con", region:2, lat:28.5383, lng:-81.3792, city:"Orlando, FL", url:"https://bsidesorlando.org", address:"", phone:"", next:"2026-09-25", when:"Sept 25–26, 2026", notes:"Workshops Friday, conference Saturday. Florida anchor — full state detail on the Florida map." },
  { name:"HackMiami", category:"con", region:2, lat:25.9510, lng:-80.1210, city:"Miami, FL", url:"https://hackmiami.com", address:"", phone:"", when:"Annual con in May + monthly meetups", notes:"South Florida's hacker con + community. Florida anchor — full state detail on the Florida map." },
  { name:"DC404 (DEF CON Group)", category:"meetup", region:2, lat:33.7550, lng:-84.3900, city:"Atlanta, GA", url:"https://www.dc404.org", address:"", phone:"", when:"Monthly — see site", notes:"Atlanta's long-running DEF CON group — talks and hands-on sessions." },
  { name:"NoVA Hackers", category:"meetup", region:2, lat:38.9586, lng:-77.3570, city:"Reston, VA", url:"https://novahackers.blogspot.com", address:"", phone:"", when:"Monthly, Monday evenings", notes:"Northern Virginia's everyone-presents meetup — huge DC-metro practitioner crowd; attend twice, then you talk." },
  { name:"Atlanta 2600", category:"meetup", region:2, lat:33.7800, lng:-84.4000, city:"Atlanta, GA", url:"https://www.2600.com/meetings", address:"", phone:"", when:"1st Friday, 5pm", notes:"Open hacker meetup — check 2600.com for the current venue." },
  { name:"DC757 (DEF CON Group)", category:"meetup", region:2, lat:36.8508, lng:-76.2859, city:"Norfolk, VA", url:"", address:"", phone:"", when:"", notes:"Hampton Roads DEF CON group — Navy-heavy crowd; confirm status via the DEF CON Groups directory." },
  { name:"Freeside Atlanta", category:"maker", region:2, lat:33.7270, lng:-84.3900, city:"Atlanta, GA", url:"https://www.freesideatlanta.org", address:"", phone:"", when:"Open house Tuesdays — see site", notes:"Atlanta's nonprofit hackerspace — electronics, machining, frequent security crossover." },
  { name:"Makers Local 256", category:"maker", region:2, lat:34.7304, lng:-86.5861, city:"Huntsville, AL", url:"https://256.makerslocal.org", address:"", phone:"", when:"", notes:"Rocket City's hackerspace — aerospace/defense engineer crowd." },
  { name:"Nova Labs", category:"maker", region:2, lat:38.9687, lng:-77.3411, city:"Reston, VA", url:"https://www.nova-labs.org", address:"", phone:"", when:"Tours + open events — see site", notes:"Large DC-metro makerspace in the middle of the NoVA tech corridor." },
  { name:"Georgia Tech", category:"school", region:2, lat:33.7756, lng:-84.3963, city:"Atlanta, GA", url:"https://www.gatech.edu", address:"", phone:"", when:"", notes:"School of Cybersecurity & Privacy; GreyHat student club and a top CTF culture." },
  { name:"Georgia Cyber Center", category:"school", region:2, lat:33.4718, lng:-81.9722, city:"Augusta, GA", url:"", address:"100 Grace Hopper Ln, Augusta", phone:"", when:"", notes:"$100M+ state cyber campus (Hull McKnight) — training, startup space, and a range, next door to Fort Eisenhower." },
  { name:"UWF Center for Cybersecurity & AI", category:"school", region:2, lat:30.5471, lng:-87.2185, city:"Pensacola, FL", url:"https://uwf.edu/centers/cybersecurity-and-ai/", address:"", phone:"", when:"", notes:"NSA-designated national cyber hub anchoring Florida's 'Cyber Coast.' Full Panhandle detail on the Florida map." },
  { name:"Virginia Tech", category:"school", region:2, lat:37.2284, lng:-80.4234, city:"Blacksburg, VA", url:"https://www.vt.edu", address:"", phone:"", when:"", notes:"Hume Center + CyberCorps; strong CTF teams (Summit/CTF@VT)." },
  { name:"Fort Eisenhower — US Army Cyber Command", category:"gov", region:2, lat:33.4200, lng:-82.1400, city:"Augusta, GA", url:"https://www.arcyber.army.mil", address:"", phone:"", when:"", notes:"ARCYBER + the Army Cyber School + NSA Georgia — why Augusta calls itself Cyber City." },
  { name:"Oak Ridge National Laboratory", category:"gov", region:2, lat:35.9300, lng:-84.3100, city:"Oak Ridge, TN", url:"https://www.ornl.gov", address:"", phone:"", when:"", notes:"National-lab cyber research at scale — internships, CyberForce-style competitions, hiring." },
  { name:"CISA", category:"gov", region:2, lat:38.8800, lng:-77.1000, city:"Arlington, VA", url:"https://www.cisa.gov", address:"", phone:"", when:"", notes:"The nation's cyber defense agency — free services, KEV catalog, advisories, and regional cybersecurity advisors in every state." },
  { name:"MITRE", category:"gov", region:2, lat:38.9245, lng:-77.2058, city:"McLean, VA", url:"https://www.mitre.org", address:"7515 Colshire Dr, McLean", phone:"", when:"", notes:"Home of ATT&CK, CVE, and CWE — the shared vocabulary of the whole industry." },

  // ---- 3 · MIDWEST ----
  { name:"THOTCON", category:"con", region:3, lat:41.8781, lng:-87.6298, city:"Chicago, IL", url:"https://thotcon.org", address:"Secret venue — revealed to ticket holders", phone:"", when:"Annual, spring — 2027 dates TBA", notes:"Chicago's beloved non-profit hacker con — cheap tickets, sells out fast. 2026 edition was May 30." },
  { name:"CypherCon", category:"con", region:3, lat:43.0389, lng:-87.9065, city:"Milwaukee, WI", url:"https://cyphercon.com", address:"Baird Center, Milwaukee", phone:"", when:"Annual, spring", notes:"Wisconsin's hacker con — villages, badge culture, big friendly Midwest crowd." },
  { name:"GrrCON", category:"con", region:3, lat:42.9690, lng:-85.6730, city:"Grand Rapids, MI", url:"https://grrcon.com", address:"DeVos Place, Grand Rapids", phone:"", next:"2026-09-24", when:"Sept 24–25, 2026", notes:"Michigan's big community con — talks, villages, and a notoriously good hallway track." },
  { name:"Kernelcon", category:"con", region:3, lat:41.2565, lng:-95.9345, city:"Omaha, NE", url:"https://kernelcon.org", address:"", phone:"", when:"Annual, spring", notes:"Omaha's hacker con — hands-on villages and CTF; strong STRATCOM-adjacent crowd." },
  { name:"Blue Team Con", category:"con", region:3, lat:41.8781, lng:-87.6300, city:"Chicago, IL", url:"https://blueteamcon.com", address:"", phone:"", when:"Annual, fall — see site", notes:"The defender-focused con — SOC, IR, detection engineering." },
  { name:"Wild West Hackin' Fest — Deadwood", category:"con", region:3, lat:44.3767, lng:-103.7296, city:"Deadwood, SD", url:"https://wildwesthackinfest.com", address:"Deadwood Mountain Grand, 1906 Deadwood Mountain Dr, Deadwood", phone:"", next:"2026-10-07", when:"Oct 7–9, 2026 · pre-con training Oct 6–7", notes:"Black Hills Infosec's con in an old-west casino town — famously beginner-friendly, heavy training focus." },
  { name:"DakotaCon", category:"con", region:3, lat:44.0061, lng:-97.1139, city:"Madison, SD", url:"https://dakotacon.org", address:"Dakota State University, Madison", phone:"", when:"Annual, spring", notes:"Free talks at Dakota State — one of the best student-to-industry pipelines in the country." },
  { name:"CornCon", category:"con", region:3, lat:41.5236, lng:-90.5776, city:"Davenport, IA", url:"https://www.corncon.net", address:"", phone:"", when:"Annual, fall", notes:"Quad Cities hacker con — includes a kids' hacker camp; exactly as corny as it sounds, in a good way." },
  { name:"Hackers Teaching Hackers", category:"con", region:3, lat:39.9612, lng:-82.9988, city:"Columbus, OH", url:"", address:"", phone:"", when:"Annual, fall — see site", notes:"Columbus community con built around peer teaching — verify current site via community socials." },
  { name:"SecKC", category:"meetup", region:3, lat:39.0997, lng:-94.5786, city:"Kansas City, MO", url:"https://www.seckc.org", address:"", phone:"", when:"Monthly, 2nd Tuesday-ish — see site", notes:"Bills itself as the world's largest recurring infosec meetup — hundreds monthly, zero gatekeeping." },
  { name:"BurbSec", category:"meetup", region:3, lat:41.8800, lng:-87.8000, city:"Chicago suburbs, IL", url:"https://www.burbsec.com", address:"Multiple suburban chapters — see site", phone:"", when:"Monthly per chapter", notes:"Chicagoland's federation of bar meetups (BurbSec East/West/North…) — where the city's infosec crowd actually hangs out." },
  { name:"DC414 (DEF CON Group)", category:"meetup", region:3, lat:43.0400, lng:-87.9100, city:"Milwaukee, WI", url:"https://dc414.org", address:"", phone:"", when:"Monthly — see site", notes:"Milwaukee's DEF CON group." },
  { name:"DC312 (DEF CON Group)", category:"meetup", region:3, lat:41.8790, lng:-87.6350, city:"Chicago, IL", url:"", address:"", phone:"", when:"", notes:"Chicago DEF CON group — confirm status via the DEF CON Groups directory." },
  { name:"MiSec", category:"meetup", region:3, lat:42.4970, lng:-83.3680, city:"Michigan (multiple cities)", url:"", address:"Chapters around Detroit, Lansing, Grand Rapids", phone:"", when:"Monthly per chapter", notes:"Michigan's statewide security community — talks + hands-on; find current chapters via community socials." },
  { name:"Pumping Station: One", category:"maker", region:3, lat:41.9312, lng:-87.7113, city:"Chicago, IL", url:"https://pumpingstationone.org", address:"3519 N Elston Ave, Chicago", phone:"", when:"Public tours Tuesdays — see site", notes:"Chicago's big nonprofit hackerspace — electronics, shops, and a security-curious crowd." },
  { name:"i3 Detroit", category:"maker", region:3, lat:42.4595, lng:-83.1347, city:"Ferndale, MI", url:"https://www.i3detroit.org", address:"1481 Wordsworth St, Ferndale", phone:"", when:"Open house Tuesdays — see site", notes:"One of the Midwest's largest member-run makerspaces." },
  { name:"Milwaukee Makerspace", category:"maker", region:3, lat:42.9950, lng:-87.9000, city:"Milwaukee, WI", url:"https://milwaukeemakerspace.org", address:"", phone:"", when:"Public tours Tuesdays — see site", notes:"Big volunteer-run space — electronics lab through full metal shop." },
  { name:"Purdue CERIAS", category:"school", region:3, lat:40.4237, lng:-86.9212, city:"West Lafayette, IN", url:"https://www.cerias.purdue.edu", address:"Purdue campus", phone:"", when:"", notes:"One of the oldest and largest academic security institutes — weekly public seminars (streamed), b01lers CTF team." },
  { name:"Dakota State University", category:"school", region:3, lat:44.0120, lng:-97.1110, city:"Madison, SD", url:"https://dsu.edu", address:"", phone:"", when:"", notes:"Small school, outsized cyber reputation — CAE in everything, direct NSA pipeline, hosts DakotaCon." },
  { name:"Iowa State — ISEAGE", category:"school", region:3, lat:42.0267, lng:-93.6465, city:"Ames, IA", url:"https://www.iseage.org", address:"Iowa State campus, Ames", phone:"", when:"", notes:"Runs Cyber Defense Competitions on its ISEAGE range for high-school through national level." },
  { name:"AFIT — Center for Cyberspace Research", category:"gov", region:3, lat:39.7800, lng:-84.0800, city:"Wright-Patterson AFB, OH", url:"https://www.afit.edu", address:"", phone:"", when:"", notes:"The Air Force's cyber graduate school and research center — Dayton's defense-cyber anchor." },

  // ---- 4 · SOUTHWEST ----
  { name:"CactusCon", category:"con", region:4, lat:33.4152, lng:-111.8315, city:"Mesa, AZ", url:"https://www.cactuscon.com", address:"Mesa Convention Center", phone:"", when:"Annual, winter", notes:"Arizona's largest hacker con — free/cheap, family-friendly, big villages." },
  { name:"HOU.SEC.CON", category:"con", region:4, lat:29.7604, lng:-95.3698, city:"Houston, TX", url:"", address:"", phone:"", when:"Annual, fall", notes:"Houston's big practitioner con — energy-sector heavy; verify current site before planning." },
  { name:"LASCON", category:"con", region:4, lat:30.2672, lng:-97.7431, city:"Austin, TX", url:"https://lascon.org", address:"", phone:"", when:"Annual, October", notes:"OWASP Austin's AppSec con — one of the best regional AppSec events in the country." },
  { name:"BSidesDFW", category:"con", region:4, lat:32.7767, lng:-96.7970, city:"Dallas, TX", url:"", address:"", phone:"", when:"Annual, fall — see site", notes:"Dallas–Fort Worth BSides — verify current edition via the Security BSides wiki." },
  { name:"BSidesSATX", category:"con", region:4, lat:29.4241, lng:-98.4936, city:"San Antonio, TX", url:"", address:"", phone:"", when:"Annual — see site", notes:"San Antonio's BSides, in one of the densest cyber job markets in the country." },
  { name:"BSidesOK", category:"con", region:4, lat:36.1540, lng:-95.9928, city:"Tulsa, OK", url:"", address:"", phone:"", when:"Annual, spring — see site", notes:"Oklahoma's BSides — verify current edition via the Security BSides wiki." },
  { name:"Texas Cyber Summit", category:"con", region:4, lat:29.4250, lng:-98.4900, city:"San Antonio, TX", url:"https://www.texascyber.com", address:"", phone:"", when:"Annual — see site", notes:"Multi-track Texas con — technical talks plus workforce/vet transition tracks." },
  { name:"Austin Hackers Association (AHA!)", category:"meetup", region:4, lat:30.2670, lng:-97.7430, city:"Austin, TX", url:"https://takeonme.org", address:"", phone:"", when:"Monthly", notes:"Storied no-vendor meetup — short turbo talks, everyone presents eventually." },
  { name:"Dallas Hackers Association", category:"meetup", region:4, lat:32.7800, lng:-96.8000, city:"Dallas, TX", url:"", address:"", phone:"", when:"1st Wednesday, evening", notes:"Dallas's monthly hacker open-mic — fire talks, big crowd; find the current venue via community socials." },
  { name:"DC505 (DEF CON Group)", category:"meetup", region:4, lat:35.0844, lng:-106.6504, city:"Albuquerque, NM", url:"", address:"", phone:"", when:"", notes:"New Mexico DEF CON group — confirm status via the DEF CON Groups directory." },
  { name:"Dallas Makerspace", category:"maker", region:4, lat:32.9757, lng:-96.8865, city:"Carrollton, TX", url:"https://dallasmakerspace.org", address:"4100 Midway Rd #106, Carrollton", phone:"", when:"Tours + open events — see site", notes:"One of the largest all-volunteer makerspaces in the US." },
  { name:"ATX Hackerspace", category:"maker", region:4, lat:30.3300, lng:-97.7000, city:"Austin, TX", url:"https://atxhs.org", address:"", phone:"", when:"Open house Tuesdays — see site", notes:"Austin's community hackerspace since 2009." },
  { name:"TX/RX Labs", category:"maker", region:4, lat:29.7270, lng:-95.3240, city:"Houston, TX", url:"https://www.txrxlabs.org", address:"", phone:"", when:"", notes:"Houston's nonprofit makerspace — classes, fab shops, electronics." },
  { name:"HeatSync Labs", category:"maker", region:4, lat:33.4152, lng:-111.8340, city:"Mesa, AZ", url:"https://www.heatsynclabs.org", address:"140 W Main St, Mesa", phone:"", when:"Open to the public most evenings — see site", notes:"Arizona's beloved storefront hackerspace." },
  { name:"Quelab", category:"maker", region:4, lat:35.0844, lng:-106.6500, city:"Albuquerque, NM", url:"https://quelab.net", address:"", phone:"", when:"", notes:"Albuquerque's makerspace/hackerspace." },
  { name:"UTSA", category:"school", region:4, lat:29.5831, lng:-98.6199, city:"San Antonio, TX", url:"https://www.utsa.edu", address:"", phone:"", when:"", notes:"Top-ranked cyber program; its CIAS created and still runs the National Collegiate Cyber Defense Competition (NCCDC)." },
  { name:"Texas A&M Cybersecurity Center", category:"school", region:4, lat:30.6188, lng:-96.3365, city:"College Station, TX", url:"https://cybersecurity.tamu.edu", address:"", phone:"", when:"", notes:"CAE across the board; huge CyberCorps scholarship cohort." },
  { name:"Arizona State — pwn.college", category:"school", region:4, lat:33.4242, lng:-111.9281, city:"Tempe, AZ", url:"https://pwn.college", address:"ASU campus, Tempe", phone:"", when:"", notes:"ASU built pwn.college — the free 'dojo' that's become the default way to learn binary exploitation; anyone can train online." },
  { name:"University of Tulsa", category:"school", region:4, lat:36.1520, lng:-95.9460, city:"Tulsa, OK", url:"https://utulsa.edu", address:"", phone:"", when:"", notes:"Storied Cyber Corps program — decades of feeding the three-letter agencies." },
  { name:"JBSA-Lackland — NSA Texas / 16th Air Force", category:"gov", region:4, lat:29.3840, lng:-98.5810, city:"San Antonio, TX", url:"https://www.16af.af.mil", address:"", phone:"", when:"", notes:"NSA Texas + Air Forces Cyber make San Antonio 'Military Cyber City USA' — the anchor of the region's cleared job market." },
  { name:"Port San Antonio", category:"gov", region:4, lat:29.3830, lng:-98.5990, city:"San Antonio, TX", url:"https://www.portsanantonio.us", address:"", phone:"", when:"", notes:"Tech/cyber campus on the old Kelly AFB — home to defense-cyber employers and the Alamo Academies pipeline." },
  { name:"Sandia National Laboratories", category:"gov", region:4, lat:35.0605, lng:-106.5360, city:"Albuquerque, NM", url:"https://www.sandia.gov", address:"", phone:"", when:"", notes:"Major national-lab cyber R&D — student internships (TITANS) and steady hiring." },
  { name:"Los Alamos National Laboratory", category:"gov", region:4, lat:35.8440, lng:-106.2857, city:"Los Alamos, NM", url:"https://www.lanl.gov", address:"", phone:"", when:"", notes:"HPC + national-security research; cyber internship programs." },

  // ---- 5 · WEST ----
  { name:"DEF CON 34", category:"con", region:5, lat:36.1350, lng:-115.1640, city:"Las Vegas, NV", url:"https://defcon.org", address:"", phone:"", next:"2026-08-06", when:"Aug 6–9, 2026", notes:"The big one — tens of thousands of hackers, 30+ villages, CTF finals, and the hub of the worldwide DEF CON Groups network." },
  { name:"Black Hat USA", category:"con", region:5, lat:36.0922, lng:-115.1745, city:"Las Vegas, NV", url:"https://www.blackhat.com", address:"Mandalay Bay, Las Vegas", phone:"", next:"2026-08-01", when:"Aug 1–6, 2026 — trainings then briefings", notes:"The corporate half of Hacker Summer Camp — trainings are world-class if someone else is paying." },
  { name:"BSides Las Vegas", category:"con", region:5, lat:36.1300, lng:-115.1500, city:"Las Vegas, NV", url:"https://bsideslv.org", address:"", phone:"", when:"Hacker Summer Camp week (early Aug)", notes:"The original BSides — runs right before/alongside DEF CON; Proving Ground track mentors first-time speakers." },
  { name:"RSA Conference", category:"con", region:5, lat:37.7841, lng:-122.4009, city:"San Francisco, CA", url:"https://www.rsaconference.com", address:"Moscone Center, San Francisco", phone:"", when:"Annual, spring", notes:"The industry mega-con — where the vendor ecosystem and CISO world gather." },
  { name:"BSidesSF", category:"con", region:5, lat:37.7800, lng:-122.4000, city:"San Francisco, CA", url:"https://bsidessf.org", address:"", phone:"", when:"Annual — RSA week", notes:"Community counterweight to RSA week — high-quality talks, very Bay Area." },
  { name:"ShellCon", category:"con", region:5, lat:33.9192, lng:-118.4165, city:"Los Angeles, CA", url:"https://shellcon.io", address:"", phone:"", when:"Annual, fall", notes:"SoCal's community security con." },
  { name:"LayerOne", category:"con", region:5, lat:34.0522, lng:-118.2437, city:"Los Angeles, CA", url:"https://www.layerone.org", address:"", phone:"", when:"Annual, spring", notes:"LA's long-running hacker con — hardware and badge culture." },
  { name:"ToorCon", category:"con", region:5, lat:32.7157, lng:-117.1611, city:"San Diego, CA", url:"https://toorcon.net", address:"", phone:"", when:"Annual, fall", notes:"One of the longest-running US hacker cons." },
  { name:"ToorCamp", category:"con", region:5, lat:48.6400, lng:-122.7800, city:"Orcas Island, WA", url:"https://toorcamp.org", address:"Doe Bay Resort, Orcas Island", phone:"", when:"Every other summer — see site", notes:"America's answer to the European hacker camps — five days of talks, radios, and lasers in the San Juans." },
  { name:"SAINTCON", category:"con", region:5, lat:40.2338, lng:-111.6585, city:"Provo, UT", url:"https://www.saintcon.org", address:"Utah Valley Convention Center, Provo", phone:"", next:"2026-10-27", when:"Oct 27–30, 2026", notes:"Utah's hacker con — 2,000+ attendees, legendary badge and community culture." },
  { name:"BSides PDX", category:"con", region:5, lat:45.5152, lng:-122.6784, city:"Portland, OR", url:"https://bsidespdx.org", address:"", phone:"", when:"Annual, fall", notes:"Portland's community security con." },
  { name:"BSides Seattle", category:"con", region:5, lat:47.6062, lng:-122.3321, city:"Seattle, WA", url:"", address:"", phone:"", when:"Annual — see site", notes:"Seattle-area BSides — verify current edition via the Security BSides wiki." },
  { name:"DC303 (DEF CON Group)", category:"meetup", region:5, lat:39.7392, lng:-104.9903, city:"Denver, CO", url:"https://www.dc303.org", address:"", phone:"", when:"Monthly — see site", notes:"One of the oldest DEF CON groups — Denver/Front Range crew." },
  { name:"DC801 (DEF CON Group)", category:"meetup", region:5, lat:40.7608, lng:-111.8910, city:"Salt Lake City, UT", url:"https://dc801.org", address:"", phone:"", when:"Weekly-ish — see site", notes:"Salt Lake's DEF CON group — runs the 801 Labs hackerspace downtown." },
  { name:"DC206 (DEF CON Group)", category:"meetup", region:5, lat:47.6100, lng:-122.3300, city:"Seattle, WA", url:"", address:"", phone:"", when:"", notes:"Seattle DEF CON group — confirm status via the DEF CON Groups directory." },
  { name:"OWASP Los Angeles", category:"meetup", region:5, lat:34.0500, lng:-118.2400, city:"Los Angeles, CA", url:"https://owasp.org/chapters/", address:"", phone:"", when:"Monthly dinner meetings — see Meetup", notes:"One of the most active OWASP chapters anywhere; co-runs AppSec California." },
  { name:"Noisebridge", category:"maker", region:5, lat:37.7625, lng:-122.4193, city:"San Francisco, CA", url:"https://www.noisebridge.net", address:"272 Capp St, San Francisco", phone:"", when:"Open most days — see wiki", notes:"SF's anarchist hackerspace — do-ocracy, no bosses; Circuit Hacking Mondays is the classic on-ramp." },
  { name:"Null Space Labs", category:"maker", region:5, lat:34.0522, lng:-118.2400, city:"Los Angeles, CA", url:"", address:"", phone:"", when:"", notes:"LA's electronics-heavy hackerspace (032) — badge-making royalty; verify current location before visiting." },
  { name:"SYN Shop", category:"maker", region:5, lat:36.1716, lng:-115.1391, city:"Las Vegas, NV", url:"https://synshop.org", address:"", phone:"", when:"Open house weekly — see site", notes:"Las Vegas's hackerspace — the local scene beyond con week." },
  { name:"801 Labs", category:"maker", region:5, lat:40.7610, lng:-111.8900, city:"Salt Lake City, UT", url:"https://www.801labs.org", address:"", phone:"", when:"", notes:"Downtown SLC hackerspace run by the DC801 crew." },
  { name:"Black Lodge Research", category:"maker", region:5, lat:47.6740, lng:-122.1215, city:"Redmond, WA", url:"https://www.blacklodgeresearch.org", address:"", phone:"", when:"", notes:"Eastside Seattle hackerspace — electronics, security, and retro computing." },
  { name:"Stanford University", category:"school", region:5, lat:37.4275, lng:-122.1697, city:"Stanford, CA", url:"https://www.stanford.edu", address:"", phone:"", when:"", notes:"Applied Cyber student group, security/crypto research; public seminars." },
  { name:"UC Berkeley", category:"school", region:5, lat:37.8719, lng:-122.2585, city:"Berkeley, CA", url:"https://cltc.berkeley.edu", address:"", phone:"", when:"", notes:"Center for Long-Term Cybersecurity + active student CTF scene." },
  { name:"UC Santa Barbara", category:"school", region:5, lat:34.4140, lng:-119.8489, city:"Santa Barbara, CA", url:"https://www.ucsb.edu", address:"", phone:"", when:"", notes:"Home turf of Shellphish — one of the winningest CTF teams ever; runs the iCTF." },
  { name:"University of Washington", category:"school", region:5, lat:47.6553, lng:-122.3035, city:"Seattle, WA", url:"https://www.washington.edu", address:"", phone:"", when:"", notes:"Security & Privacy Research Lab; Batman's Kitchen student CTF team." },
  { name:"Lawrence Livermore National Laboratory", category:"gov", region:5, lat:37.6819, lng:-121.7680, city:"Livermore, CA", url:"https://www.llnl.gov", address:"", phone:"", when:"", notes:"National-lab cyber + HPC; student internships and steady hiring." },
  { name:"Pacific Northwest National Laboratory", category:"gov", region:5, lat:46.2804, lng:-119.2752, city:"Richland, WA", url:"https://www.pnnl.gov", address:"", phone:"", when:"", notes:"Major federal cyber research portfolio — grid/OT security especially." },
  { name:"Space ISAC", category:"gov", region:5, lat:38.8339, lng:-104.8214, city:"Colorado Springs, CO", url:"https://s-isac.org", address:"", phone:"", when:"", notes:"Space-sector threat sharing HQ'd in the Springs — the anchor of the local space-cyber scene." },
];
