// Build regions.js for the US map: per-state polygons (STATE_GEO) plus the
// 5 super-regions (REGION_GEO), derived in-file from the state geometries.
// Usage: node scripts/make-regions.js <us-states.json> regions.js
const fs = require('fs');
const src = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));

// name -> [postal code, region]  ·  1 NE  2 SE  3 MW  4 SW  5 W
const STATE_META = {
  'Connecticut':['CT',1],'Maine':['ME',1],'Massachusetts':['MA',1],'New Hampshire':['NH',1],
  'Rhode Island':['RI',1],'Vermont':['VT',1],'New Jersey':['NJ',1],'New York':['NY',1],
  'Pennsylvania':['PA',1],'Delaware':['DE',1],'Maryland':['MD',1],'District of Columbia':['DC',1],
  'Virginia':['VA',2],'West Virginia':['WV',2],'Kentucky':['KY',2],'Tennessee':['TN',2],
  'North Carolina':['NC',2],'South Carolina':['SC',2],'Georgia':['GA',2],'Florida':['FL',2],
  'Alabama':['AL',2],'Mississippi':['MS',2],'Arkansas':['AR',2],'Louisiana':['LA',2],'Puerto Rico':['PR',2],
  'Ohio':['OH',3],'Michigan':['MI',3],'Indiana':['IN',3],'Illinois':['IL',3],'Wisconsin':['WI',3],
  'Minnesota':['MN',3],'Iowa':['IA',3],'Missouri':['MO',3],'North Dakota':['ND',3],
  'South Dakota':['SD',3],'Nebraska':['NE',3],'Kansas':['KS',3],
  'Texas':['TX',4],'Oklahoma':['OK',4],'New Mexico':['NM',4],'Arizona':['AZ',4],
  'Colorado':['CO',5],'Wyoming':['WY',5],'Montana':['MT',5],'Idaho':['ID',5],'Utah':['UT',5],
  'Nevada':['NV',5],'Washington':['WA',5],'Oregon':['OR',5],'California':['CA',5],
  'Alaska':['AK',5],'Hawaii':['HI',5],
};

// Trim coordinate precision to 3 decimals (~110 m) to keep the file small.
const round = c => Array.isArray(c[0]) ? c.map(round) : [Math.round(c[0]*1000)/1000, Math.round(c[1]*1000)/1000];

const states = [];
const missing = [];
for (const f of src.features){
  const meta = STATE_META[f.properties.name];
  if (!meta){ missing.push(f.properties.name); continue; }
  const g = f.geometry;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  states.push({
    type:'Feature',
    properties:{ code: meta[0], name: f.properties.name, region: meta[1] },
    geometry:{ type:'MultiPolygon', coordinates: polys.map(round) }
  });
}
if (missing.length) console.error('UNASSIGNED:', missing.join(', '));
states.sort((a, b) => a.properties.code.localeCompare(b.properties.code));

const out = `/* Generated by scripts/make-regions.js from PublicaMundi us-states.json.
   STATE_GEO — one MultiPolygon per state/territory (code, name, region).
   REGION_GEO — the 5 super-regions, derived below by grouping states. */
const STATE_GEO = ${JSON.stringify({type:'FeatureCollection', features:states})};
const REGION_GEO = { type:'FeatureCollection', features:[1,2,3,4,5].map(id => ({
  type:'Feature', properties:{ region:id },
  geometry:{ type:'MultiPolygon',
    coordinates: STATE_GEO.features.filter(f => f.properties.region === id)
      .flatMap(f => f.geometry.coordinates) }
})) };
`;
fs.writeFileSync(process.argv[3], out);
console.log('wrote', process.argv[3], (out.length/1024).toFixed(0)+'KB,', states.length, 'states');
